// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD7PsqAKpjfSRoj5FrzjZI0QId1gY092A',
    appId: '1:61429305321:web:6e7f33f9dee128c3be4578',
    messagingSenderId: '61429305321',
    projectId: 'business-app-portfolio-2026',
    authDomain: 'business-app-portfolio-2026.firebaseapp.com',
    storageBucket: 'business-app-portfolio-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVtbvioNrSxcIsFnahMu-5IrKpf0vEzLo',
    appId: '1:61429305321:android:57420a7429574044be4578',
    messagingSenderId: '61429305321',
    projectId: 'business-app-portfolio-2026',
    storageBucket: 'business-app-portfolio-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDocddVYN5etLPbd_CBIXtDuJYAMSrk2rc',
    appId: '1:61429305321:ios:0babd5b590c096c7be4578',
    messagingSenderId: '61429305321',
    projectId: 'business-app-portfolio-2026',
    storageBucket: 'business-app-portfolio-2026.firebasestorage.app',
    iosBundleId: 'com.business.app.businessApp',
  );
}
